// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClkANjg6xg8Emna-lj0M2buykyZ-hlPt8',
    appId: '1:997594608982:web:ba2d7ab476a8db6c3092f7',
    messagingSenderId: '997594608982',
    projectId: 'unichat-2acd0',
    authDomain: 'unichat-2acd0.firebaseapp.com',
    databaseURL: 'https://unichat-2acd0-default-rtdb.firebaseio.com',
    storageBucket: 'unichat-2acd0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOfPIFSnd8YyoAfWusuiX0vyKA4ImCi4g',
    appId: '1:997594608982:android:c56e87565dbc0d343092f7',
    messagingSenderId: '997594608982',
    projectId: 'unichat-2acd0',
    databaseURL: 'https://unichat-2acd0-default-rtdb.firebaseio.com',
    storageBucket: 'unichat-2acd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb-sj1kfgSQsvGq4qtwRspzxWdW5FNcVY',
    appId: '1:997594608982:ios:600485c59c9b91113092f7',
    messagingSenderId: '997594608982',
    projectId: 'unichat-2acd0',
    databaseURL: 'https://unichat-2acd0-default-rtdb.firebaseio.com',
    storageBucket: 'unichat-2acd0.appspot.com',
    iosBundleId: 'com.example.unichat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb-sj1kfgSQsvGq4qtwRspzxWdW5FNcVY',
    appId: '1:997594608982:ios:c9e953e83deb94f53092f7',
    messagingSenderId: '997594608982',
    projectId: 'unichat-2acd0',
    databaseURL: 'https://unichat-2acd0-default-rtdb.firebaseio.com',
    storageBucket: 'unichat-2acd0.appspot.com',
    iosBundleId: 'com.example.unichat.RunnerTests',
  );
}
