// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1C4G8TUUqCwu2WW6vu5lgSHHADlOEYNA',
    appId: '1:157783120671:web:6f6a7ba5af3038921b2e2a',
    messagingSenderId: '157783120671',
    projectId: 'unichat-ca129',
    authDomain: 'unichat-ca129.firebaseapp.com',
    databaseURL: 'https://unichat-ca129-default-rtdb.firebaseio.com',
    storageBucket: 'unichat-ca129.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdumku6bs2f4ke9pr6WjkhZQp_E1rUB2Q',
    appId: '1:157783120671:android:0d04cdefe1d0631e1b2e2a',
    messagingSenderId: '157783120671',
    projectId: 'unichat-ca129',
    databaseURL: 'https://unichat-ca129-default-rtdb.firebaseio.com',
    storageBucket: 'unichat-ca129.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtYhLQIiY-Xw4gybERdY6oFiMso0sjUEo',
    appId: '1:157783120671:ios:ff1b6ed80bbb98051b2e2a',
    messagingSenderId: '157783120671',
    projectId: 'unichat-ca129',
    databaseURL: 'https://unichat-ca129-default-rtdb.firebaseio.com',
    storageBucket: 'unichat-ca129.appspot.com',
    iosBundleId: 'com.example.unichat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtYhLQIiY-Xw4gybERdY6oFiMso0sjUEo',
    appId: '1:157783120671:ios:0b8eb3f26e6eec8e1b2e2a',
    messagingSenderId: '157783120671',
    projectId: 'unichat-ca129',
    databaseURL: 'https://unichat-ca129-default-rtdb.firebaseio.com',
    storageBucket: 'unichat-ca129.appspot.com',
    iosBundleId: 'com.example.unichat.RunnerTests',
  );
}
